### PR TITLE
Create 自由主义

### PR DESCRIPTION
**Pull request by im-liu**

### CODE REVIEW

**Comment by the-run-philosophy** [comment]
@im-liu  请将文件改为.md 后缀谢谢

**Review by the-run-philosophy — CHANGES_REQUESTED** [review]
请将文件改为.md 后缀谢谢

**Comment by im-liu** [comment]
@the-run-philosophy 已修改.md，谢谢

**Comment by jiayouba233** [comment]
> @the-run-philosophy 已修改.md，谢谢

请修正MarkDown语法错误

**Comment by im-liu** [comment]
updated format

**Comment by XifeiNi** [comment]
isn't this just mere copy for wikipedia? Maybe include a reference on the top to declare the originality of such issue

**Comment by jiayouba233** [comment]
> updated format

Actions检查没有通过......

**Pull request merged**
