### PR TITLE
更新

### PR DESCRIPTION
**Pull request by jiayouba233**
1.@himself65 之前写的Cl并没有检查所有MarkDown文件，修复此Bug
但目前检查到HTML部分会出Bug，面包说ta会修的（
img
2.目前的Error实在太多，先修复一部分语法错误（修不动了

### CODE REVIEW

**Comment by the-run-philosophy** [comment]
@jiayouba233  这个有问题，for example, 我不认为在英文附近加入空格是正确的做法

**Comment by Himself65** [comment]
> @jiayouba233 这个有问题，for example, 我不认为在英文附近加入空格是正确的做法

I don't think you know the markdown

**Review by Himself65 — APPROVED** [review]
LGTM

**Review by Himself65 — CHANGES_REQUESTED** [review]
Please squash the commits. You mess up your git commits

**Comment by jiayouba233** [comment]
> Please squash the commits. You mess up your git commits

I think I have already fixed.

**Review by Himself65 — APPROVED** [review]
Seems like you don’t know what is squash, I will do that by clicking…

**Pull request merged**
