### PR TITLE
The run philosophy organization main

### PR DESCRIPTION
**Pull request by Xnor-bear**

### CODE REVIEW

**Comment by the-run-philosophy** [comment]
字母和数字前后的空格有很大问题，请手动修复。

**Review by the-run-philosophy — CHANGES_REQUESTED** [review]
字母和数字前后的空格有很大问题，请手动修复。

**Comment by the-run-philosophy** [comment]
和https://github.com/The-Run-Philosophy-Organization/run/pull/219 只选一个？请把重复的pr关掉

**Comment by Himself65** [comment]
we can use https://github.com/markdownlint/markdownlint to automatally check the format issue

**Comment by Himself65** [comment]
> we can use https://github.com/markdownlint/markdownlint to automatally check the format issue

Refs: #233

**Pull request closed without merging**
